# Introduction to NumPy
---

### Import of Python Libraries
- Import library via command `import name as nametag`, e.g. `import numpy as np`
- This allows us to call all functions which are part of the library using the nametag, e.g. `np.array()` to create a numpy array or `np.sum(values)` to sum over `values`
- Official NumPy Tutorial: https://numpy.org/learn/
- Here we will just cover a couple of functions which might be of importance for our Opinion Dynamics project

In [8]:
# Import Numpy
import numpy as np

### Creation of NumPy Arrays:
- The core of NumPy are numpy arrays which essentially are matrices
- The whole library is based on using those arrays for numerics
- We can either build those arrays by hand (using specific values) or use a numpy based function

In [9]:
# 2D Matrix by Hand:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('2D matrix of 3 row and column elements:\n', arr1, '\n')

# 6x4 Matrix of random values inside range [-10,10)
arr2 = np.random.uniform(low=-10, high=10, size=(6,4))

print('6x4 Matrix of random values inside range [-10,10):\n', arr2, '\n')

# 10 linearly spaced values in between 1a and 10 (row-vector)
arr3 = np.linspace(start=1, stop=10, num=10)

print('10 linearly spaced values in between 1a and 10:\n', arr3, '\n')

# Transform the previous row-vector to a column-vector
arr4 = arr3[:,np.newaxis]

print('Previous row-vetor as column-vector:\n', arr4, '\n')

2D matrix of 3 row and column elements:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

6x4 Matrix of random values inside range [-10,10):
 [[ 8.06914903 -8.1764998  -3.10416737 -1.34053246]
 [ 8.96994721 -0.08403376  6.95991752  5.22273781]
 [ 0.14753182  0.21683464  5.09955459 -5.5139866 ]
 [ 3.70759999 -3.87033809 -6.13699417 -2.43035472]
 [ 5.93691552  1.29979269  1.13547119  5.43304535]
 [-7.15608799  9.56082048  2.4920498   6.60599   ]] 

10 linearly spaced values in between 1a and 10:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

Previous row-vetor as column-vector:
 [[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]] 



### Accessing elements in NumPy Arrays:
- Use square brackets to access an element
- As with all of Python, indexing starts at zero, i.e. element at index zero would be the first elements etc..
- Example: Use `arr1[1,2]` to get the element at row=1 and column=2
- When using `:`, we can access multiple elements at once or get portions of an array
- Example: `arr1[1:3,0:2]` to get all elements from row=1 to row=3 and column=0 to column=2. The upper bound is not included
- If we want all elements from the first or until the last index we can also just write `arr1[1:,:2]` which would be the same as above
- When trying to access a non-existing index, an error is raised.

In [10]:
print(arr1[1:3,0:2], '\n')
print(arr1[1:,:2], '\n')
print(arr2[2:,:], '\n')

[[4 5]
 [7 8]] 

[[4 5]
 [7 8]] 

[[ 0.14753182  0.21683464  5.09955459 -5.5139866 ]
 [ 3.70759999 -3.87033809 -6.13699417 -2.43035472]
 [ 5.93691552  1.29979269  1.13547119  5.43304535]
 [-7.15608799  9.56082048  2.4920498   6.60599   ]] 



### Numerics with NumPy Arrays:
- Numpy arrays are always combined element-wise
  - `arr_a + arr_b` will add element-wise
  - `arr_a * arr_b` will multiply element-wise
  - `arr_a @ arr_b` will perform a matrix multiplication

In [11]:
arr_a = np.random.randint(low=-5,high=5,size=(3,3))
arr_b = np.random.randint(low=-5,high=5,size=(3,3))

print("Array a:\n", arr_a, "\n")
print("Array b:\n", arr_b, "\n")
print("Array a + Array b:\n", arr_a+arr_b, "\n")
print("Array a * Array b:\n", arr_a*arr_b, "\n")
print("Array a @ Array b:\n", arr_a@arr_b, "\n")

Array a:
 [[-4 -5  4]
 [-5  4 -1]
 [ 1  1 -1]] 

Array b:
 [[-5 -5 -5]
 [-1 -5  1]
 [-4 -2 -1]] 

Array a + Array b:
 [[ -9 -10  -1]
 [ -6  -1   0]
 [ -3  -1  -2]] 

Array a * Array b:
 [[ 20  25 -20]
 [  5 -20  -1]
 [ -4  -2   1]] 

Array a @ Array b:
 [[ 9 37 11]
 [25  7 30]
 [-2 -8 -3]] 



- Some useful numpy functions:
  - `np.sum(arr)` to calculate the sum across all elements in `arr`
  - `np.mean(arr)` to calculate the mean across all elements in `arr`
  - `np.abs(arr)` to return the absolute value of each element in `arr`
  - `arr.shpae` to return the number of elements per dimension of `arr`, e.g. if `arr` is 2D, calling `arr.shape[0]` would return number of rows and `arr.shape[1]` number of columns
  - `np.random.choice(arr)` randomly sample a value from `arr`
  - `np.where(condition)` returns all indices where condition is True, e.g. `np.where(arr==1)` would return all indices where elements of `arr` are 1
- Most function allow to define the `axis` argument which allows us to specify over which dimension we want to apply the function
  - If `arr` is a 2D array, `np.sum(arr, axis=0)` sums along rows
  - If `arr` is a 2D array, `np.mean(arr, axis=1)` averages along columns

In [12]:
print("Array a:\n", arr_a, "\n")
print("Sum along rows:\n", np.sum(arr_a,axis=0), "\n")
print("Mean along columns:\n", np.mean(arr_a,axis=1), "\n")

Array a:
 [[-4 -5  4]
 [-5  4 -1]
 [ 1  1 -1]] 

Sum along rows:
 [-8  0  2] 

Mean along columns:
 [-1.66666667 -0.66666667  0.33333333] 



### Functions in Python
- In General it is adventageous to summarize mutiple lines of code in function and seperate your code in different concerns
- Using `def function_name(argument1, argument2):` to define a function called `function_name` which takes the arguments `argument1` and `argument2`
- The code executed when calling the function is inside the function body
- If the funciton should return a value e.g. `x`, finish the function body via `return x`

In [21]:
def return_where_value_matches(arr1, arr2, value):
    """Function which returns all elements of arr1 at which arr2 equals values"""

    idx     = np.where(arr2==value)
    arr3    = arr1[idx]

    return arr3

shape   = (10,10)
arr_1   = np.random.randint(low=-5,high=5,size=shape)
arr_2   = np.random.randint(low=-5,high=5,size=shape)

print("Array 1:\n", arr_1, "\n")
print("Array 2:\n", arr_2, "\n")

arr_3   = return_where_value_matches(arr1=arr_1, arr2=arr_2, value=1)

print("Array 3:\n", arr_3, "\n")

Array 1:
 [[ 4 -5 -5 -5 -1 -1  4 -3  3 -1]
 [-5 -5 -2 -2  1  4  3 -1 -5  4]
 [ 4  1  2 -3 -5  3  3 -3 -4 -2]
 [-4 -2 -1 -2 -2 -2 -4 -4 -1  1]
 [-1  2  4 -2  2  3 -4  3 -4 -5]
 [-5 -3 -1 -1  0  2  4  3  1  1]
 [ 0 -2  4  1  2  3 -1  4  1 -3]
 [-5 -5  2 -4  3  4  1  1  4  4]
 [ 2  2  1  2 -2 -2  0  4  2  2]
 [-1  1 -2  1  4  2 -1  1  2 -3]] 

Array 2:
 [[-5  0  2 -4  0  4  2  4 -5 -2]
 [-5  2  1  2  1  3 -1  2 -4 -3]
 [ 0  0 -2  3 -2 -2 -4  1  0  0]
 [-1  1 -1  3 -5 -3 -4  4 -1 -5]
 [ 2  4  0 -2 -5 -1  0  2  3 -4]
 [ 3 -2 -2  3 -2  0  1  0  0  1]
 [-4 -4 -2 -1 -2  0 -2 -2  1  0]
 [-2 -4  3  2  4 -4 -4  2  3  1]
 [ 4  3  2  3 -5 -2 -1 -4  4 -3]
 [ 3 -4  0  3 -2  0 -3 -2 -5 -3]] 

Array 3:
 [-2  1 -3 -2  4  1  1  4] 

